### ISSUE TITLE
Loot chests in structures 

### ISSUE THREAD

**Issue by King65868** [Saereth/inferno_issues#13]
**Describe the bug**
Structure chests have no loot in them. 

**To Reproduce**
Go look for a structure, open a chest. 

**Expected behavior**
Expected loot.

**Comment by Saereth** [comment]
Please note waypoints of any broken loot checks here please so I can investigate

**Comment by King65868** [comment]
-37 48 7 is a spot I found with empty chests

**Comment by Saereth** [comment]
this should be fixed in the new update

**Comment by King65868** [comment]
Found another one, 277 50 -606.
