### ISSUE TITLE
[Recipes] Zensummoning Overworld Mobs

### ISSUE THREAD

**Issue by TheonlyTazz** [Saereth/inferno_issues#17]
Add zensummoning for following mobs: (I want to implement those)

chicken:  (i think Saereth had an idea for this)
pigs: 4 Bacon, 3 Carrot, Dark gem;  catalyst: Egg
cows: 4 Beef Patty, 3 Wheat, Dark gem; catalyst: Egg  (Beef from Strider Slice in Spirit Fire)
sheep: 4 Mutton Chops, 3 Wool, Dark Gem; catalyst: Egg (Mutton from Ham in Spirit Fire  (Ham from knifing pigs or hoglins))
Wolf: 4 Bones, 3 Rotten Flesh, Dark Gem; catalyst: Egg

**Comment by Saereth** [comment]
all approved except pigs, prefer them to farm hoglins

**Comment by TheonlyTazz** [comment]
this would then also be smart to remove the minecolonies pig pen and perhaps disable/hide from jei
