### ISSUE TITLE
[Mod Idea] Doggy Talents

### ISSUE THREAD

**Issue by TheonlyTazz** [Saereth/inferno_issues#18]
**Describe the Idea**
To increase the Survivability of the player, they could summon Wolves to tame. Adding Doggy Talents would give wolves/dogs more indepth

**Link**
https://www.curseforge.com/minecraft/mc-mods/doggy-talents

**Comment by TheonlyTazz** [comment]
In addition, if we want companions like a Wolf we could also add:
https://www.curseforge.com/minecraft/mc-mods/friendly-fire

**Comment by Saereth** [comment]
this is a great addition, we'll get it in for the next major update
