### ISSUE TITLE
unify common metal byproducts

### ISSUE THREAD

**Issue by IRSmoh** [Saereth/inferno_issues#19]
plates
gears
wire?
smelted ore types?

may just be industrial contraptions and immersive (when looking at plates)

honeys lmao

**Comment by random51** [comment]
Looks like somebody started on this but forgot the Immersive Engineering Hammer.

It still makes Immersive plates, which are useless. Not sure if you want it that way or if you want it to make TE/FTBIC plates so we can make a plate with it and then use that plate to make the plate mold in the smeltery.

**Comment by Saereth** [comment]
https://github.com/Saereth/inferno_issues/issues/44
