### ISSUE TITLE
[Crash Log] Troxarus Crash Log

### ISSUE THREAD

**Issue by TheonlyTazz** [Saereth/inferno_issues#2]
**Describe the bug**
repeatedly crashed

**To Reproduce**
random

**Expected behavior**
no crash

**Crash Log or Latest.log**
https://gist.github.com/TheonlyTazz/e0dcd5c5ec019290e2af83f231474da9

**Additional context**

**Comment by Saereth** [comment]
Duplicate
https://github.com/Saereth/inferno_issues/issues/1
