### ISSUE TITLE
Misc collected thoughts from a day of getting up to speed on Mine Colonies

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#25]
So some misc collected thoughts. I've been able to get a good long play today with some MineColonies so..

* Despite being on the nether roof, biome location matters to what things spawn in your base. Forests get Hoglins, which are very nasty.
* I'm currently in a vanilla MC biome. I currently get say... 50% zombie piglin's, 30% volines, 20% piglins.
* Both types of piglins tend to attack colonists fairly quickly. Volines only attack the player and home in on them.
* I've been losing a lot of colonists. I've basically had three "days" in a row where someone died, and colonists won't work on the next day. Lots of waiting.
* The current Emerald torch that was added to the colony quest doe snot prevent either type of piglins or volines so far. I don't know about hoglins as I left the biome before trying the torch.
* Through all this, I had the emerald torch up, it doesn't prevent those three mob spawns inside my base. I can hear spiders and ghasts below my base, but nothing else spawned up top.
* Therefore emphasise in quest text to get 2x guard towers up asap. 1x probably isn't enough. Maybe even gate it. If spawns are supposed to happen in the base, anyway
* The mine doesn't seem to teleport through bedrock. The miner will mine at about -4 Y from the lowest location they can reach then stop. They do need a ladder and breakable blocks to get deeper. I know you said something about a bedrock breaking spell so maybe this will be fine
* Miners also currently need specific ladders, but you said you were gonna fix that
* Long Colonies sleep time is still quite annoying. Not sure if it needs reducing.
* Supply camp needs a warning it's a one time use only. Needs an admin command to remove if it's not where you want it.

**Comment by Saereth** [comment]
- new torch should help with the aggro issues
- will turn down voline spawn rate
- I still think we need a questline explaining the importance of guard towers, upgrading them with research and explaining what tier of tools they can use at each tower level as thats very unclear now
- I fixed the ladder recipe back to just requiring sticks
- colony sleep time is normal mc sleep time but ars has a ritual to make it day which will work for the colonists
- I changed the setting so you can move and place multiple camps now
-
