### ISSUE TITLE
Capsule structures are of mixed heights (/cannot be rotated)

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#26]
**Describe the bug**
It might be a faff, but it might also be better to standardise the capsules a bit. They current have three different depths. I think more than half of players won't care. The tidy or anal players will get pretty annoyed at getting the capsules to line up well. I'm trying to be tidy so this is what I found:

* Builder and tavern have the same depth. If you toss them onto bedrock, they are level.
* Guard towers are one higher. Throw onto bedrock and they are higher than the builder.
* Others are one lower, e.g. suppliers and warehouse. Tossing this onto bedrock will be lower than a builder.

Structures also cannot be rotated because of certain blocks in the design. This is probably a hard limitation in the capsules mod. MineColonies seems to be able to know what it's doing here.

**To Reproduce**
Tossing these capsules onto ground of the same height results in a different height of the result structure

**Expected behavior**
I would expect the ground level of all capsule structures to be the same height

**Comment by TheonlyTazz** [comment]
yes this could be changed by forcing only x amount of blocks under level ground, but some minecolonies buildings have a basement, and some don't. this makes it hard to find 1 unified height for all

**Comment by Delfayne** [comment]
Yea, I'm not gonna push for this heavily, just warning that I think you'll get tickets about this in live also. Could add a dummy block on the base of some of the capsules to bring the heights up. Tedious work though.

**Comment by Delfayne** [comment]
This might be better handled as random51 is doing by recessing structures into the bedrock some. That also means any non-capsule buildings also don't need massive quantities of netherrack to build the basements.
Especially when we will have a way to punch through the bedrock more easily. 

I think overall we can solve this ticket by documenting these other approaches well.

**Comment by Saereth** [comment]
sounds good
