### ISSUE TITLE
07/04: Today's progression blocker report

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#27]
As requested, listing currently known progression blockers:

* Sifter is available at T1 Uni
* Sifter does not work without a mesh.
* Fletcher can make the String mesh (implied to be the earliest mesh - needs T1 Sifter to use). Fletcher needs T2 Uni
* Stonemason can make Flint mesh, but this needs a T3+ Sifter to use.
* T2 uni needs these things we currently can't get: pumpkins, green dye, yellow dye, spruce wood
* Only links in JEI to green dye are cactus. Yellow dye is overworld flowers.
* You said Dye is supposed to come from dye bees, but they might need flowers.
* Bone mealing grass for flowers only gets grass.
* T3 builder needs Blue Orchids (not dye)

**Comment by Saereth** [comment]
green dye adding kelp to fish loot with a recipe to make green dye, along with water bottles
yellow dye I'll fix grass loot tables for bone meal
will add a hexerei cauldron recipe for green die +sugar cane + few other things to make a cactus so thats more easily renewable
pumpkin I still want from sifter so we'll just give those out via a quest I suppose and remove the seed crafting recipe
We should add a quest on how to make cyan dye from lapis/apetite

**Comment by Delfayne** [comment]
If that's the plan for pumpkin be aware that there's other buildings that need them (farms for instance) so it's quite possible to lose the one that you need for the university. Just a think to keep in mind!

**Comment by Saereth** [comment]
We are also giving out a string mesh with the sifter quest now and removing the requirements for the meshes entirely so it should be fine
