### ISSUE TITLE
Crash with MineColonies simple quarry

### ISSUE THREAD

**Issue by random51** [Saereth/inferno_issues#28]
**Describe the bug**
Place a simple quarry on top of the nether. Go into build options and tell it to build. Crashes the client.

**To Reproduce**
Same as above

**Expected behavior**
No crash.

**Crash Log or Latest.log**

https://pste.ch/radopoyusa.pl

**Comment by random51** [comment]
I tried a few blocks below the nether and it crashed there too. The ui wants me to use the build tool to place this but it doesn't show up as an option with the build tool so I'm manually placing it.

**Comment by Saereth** [comment]
this should be resolved in the next update v0.1.5 if not let me know and reopen
