### ISSUE TITLE
Music Breaks switching menus in the main menu

### ISSUE THREAD

**Issue by BlocksterA** [Saereth/inferno_issues#3]
**Describe the bug**
Basically the music restarts or doesn't play when you switch menu's in the main menu.

**To Reproduce**
1. Launch minecraft
2. switch menus in main menu ex: going to settings
**Expected behavior**
The music doesn't stop
**Screenshots**

**Crash Log or Latest.log**

**Additional context**

**Comment by BlocksterA** [comment]
Would recommend checking out music triggers for the custom music.

**Comment by Saereth** [comment]
Tracking with author
https://github.com/Keksuccino/FancyMenu/issues/299
