### ISSUE TITLE
Consider increasing Ender Pearl drop rate from fishing in Warped biomes

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#30]
Perhaps it was just my bad luck, but 8 full fishing rods netted one ender pearl. In comparison that's about 1-2 ghast fireballs per rod, 3-4 procs of lapis, 1x blaze charm, and about 4x red coral. 

It got me one bonsai pot early, but I probably wanted about three. The rate where it's at might be too annoying.

**Comment by Saereth** [comment]
double drops
