### ISSUE TITLE
Some nice changes 

### ISSUE THREAD

**Issue by King65868** [Saereth/inferno_issues#35]
Bloodshroon stem should have the ability to be turned into charcoal like the other wood types of the nether. 
Glowcystals should drop themselves instead of glowstone without the use of silk touch.

**Comment by Delfayne** [comment]
I note Hellbark also does not charcoal.

**Comment by Delfayne** [comment]
Mine Colonies Field could also use Straw bales from Farmers in addition to vanilla Hay

**Comment by Saereth** [comment]
dont think I can set variant replacement blocks for the farm unfortunately, I'll make hellbark and bloodshroom stems. Is there a need for the glowcrystals to not require silk touch progression wise?

**Comment by King65868** [comment]
Not a need, but would be nice

**Comment by TheonlyTazz** [comment]
> Mine Colonies Field could also use Straw bales from Farmers in addition to vanilla Hay

could change to straw bales, but you should have access to vanilla wheat and hayblocks, changing this wouldnt make much diffrence.
Sae can close this issue once he is done with hellbark and bloodshroom stems
