### ISSUE TITLE
Cobblegen capsule doesn't place where preview suggest when rotated.

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#37]
**Describe the bug**
As per title.

**To Reproduce**
I was facing west. Preview placing Cobblegen capsule. Rotate 90'. Use Capsule. Cobblegen appears rotated, but + 7 tiles west than previewed.

**Expected behavior**
Placed where preview suggested.

**Screenshots**
From:
![2022-07-07_21 31 08](https://user-images.githubusercontent.com/97418063/177773970-bfa83746-9257-48e7-8e24-37e3512926d4.png)

To:
![2022-07-07_21 31 11](https://user-images.githubusercontent.com/97418063/177773990-b5520076-1e86-42a3-b950-28e59b1fcb96.png)

**Comment by Saereth** [comment]
I had this happen too, pretty annoying tbh but I doubt it will get fixed as it would require rewriting the placement logic which the dev didnt seem to keen to mess with. I'm open to alternative though

**Comment by Saereth** [comment]
this is being removed for a cobblegen block
