### ISSUE TITLE
Madness is too dangerous

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#41]
The Madness illness is currently a problem.

My current situation is that all seven of my colonists finally succumbed to madness. All routes of progression to the materials that can cure madness are locked behind further Colonies progression.

Judging from the vanilla version of this illness, the original cure is not gated behind doing more Colonies. Since I need colonists to advance to a cure, and I have no colonists that will work, and I cannot hire additional colonists, I am effectively soft locked.

The only reason this isn't a hard lock is that I could drop all my colonists in lava and get a new batch.

**Comment by Saereth** [comment]
taking several steps to help mitigate this

**Comment by Saereth** [comment]
with all the things we've done to make sourceberries easier to obtain im hoping this is ok now, gonna keep this open for now though
