### ISSUE TITLE
Building a T1 Sifter or Crusher via Builder (not capsule) requests bedrock blocks

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#42]
When building a Sifter, the Builder requests about 4-5 Bedrock when building. 

![2022-07-08_16 36 32](https://user-images.githubusercontent.com/97418063/177959094-9bbb6e77-ff57-41af-b254-6ae2f1027b39.png)

The Sifter was built at Bedrock+1
![2022-07-08_16 31 04](https://user-images.githubusercontent.com/97418063/177958978-2956798f-04e1-4a9a-a54e-7f8822c99aa5.png)

When choosing to build the structure, bedrock does not appear in the materials list.
Insta-building a floating T1 Sifter, and mining it out does not reveal bedrock.
I have not tested building a floating T1 sifter via Builder

**Comment by Delfayne** [comment]
I am also getting this for a T1 Crusher

![image](https://user-images.githubusercontent.com/97418063/178168934-bcda6337-f613-4004-8f7d-a20c03afc5ee.png)
![image](https://user-images.githubusercontent.com/97418063/178168956-dda173e5-68ff-4b6f-bc66-7716d9fbff3b.png)

**Comment by Delfayne** [comment]
Interestingly while the crusher requested these blocks, he later forgot about them and built it anyway when all other prereqs were satisfied

**Comment by Saereth** [comment]
do your builders seem to be destroying bedrock currently when they mind? this may be a result of removing the indestructible tag on bedrock for minecolonies, if they arent destroying the bedrock with that tag removed however its not helping us regardless

**Comment by Delfayne** [comment]
I didn't know we'd removed it yet. I have not noticed Builders destroying bedrock yet.

**Comment by Delfayne** [comment]
![2022-07-11_12 01 08](https://user-images.githubusercontent.com/97418063/178180803-41699d64-64ba-4f33-ab6c-97ee05e5be5a.png)

Fresh new mine just created, no bedrock dug by Colonist

**Comment by Saereth** [comment]
ok looks like that tag is just causing problems and not helping then, this wasnt happening before that change so I'll revert it for tomorrow's update

**Comment by Saereth** [comment]
this shouldnt happen now, minecolonies updated
