### ISSUE TITLE
T1/T2 Structures requiring Overworld Mats thread

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#43]
A collection of T1 buildings requiring overworld materials:

T1 Sawmill requires 4x oak wood planks:
![2022-07-09_08 26 40](https://user-images.githubusercontent.com/97418063/178081736-494fa615-2ee7-4466-b87e-7b3943e05177.png)
 
Oak Planks -> Warped Planks

**Comment by Delfayne** [comment]
Guard Tower - doesn't use overworld 'mats' but..
Ladder -> Crimson / Warp Ladder
![2022-07-09_08 37 22](https://user-images.githubusercontent.com/97418063/178082249-29d8e41b-ca26-4fde-b803-a420df5a56f5.png)

**Comment by Delfayne** [comment]
Ditto Fisher
Ladder -> Crimson / Warp Ladder
![2022-07-09_08 38 37](https://user-images.githubusercontent.com/97418063/178082319-a5fe91bf-5333-4813-a2b2-83704b8b10df.png)

**Comment by Delfayne** [comment]
T2 Warehouse: Oak Stairs -> Warped Stairs

**Comment by Delfayne** [comment]
T2 Sawmill
Oak stair -> crimson stair
Oak Log -> Hellbark (or similar) Log. Reason being this already has crimson/warp together
But this being the sawmill OW logs are probably not unreasonable

![2022-07-10_17 05 50](https://user-images.githubusercontent.com/97418063/178136595-c9e395fb-c63d-4567-bac7-3ce12f39f9c8.png)

**Comment by Delfayne** [comment]
Not T1/2 here, but T3:
T3 Composter requires Vines and Ferns, both of which are presently unobtainable.

**Comment by Saereth** [comment]
ok all these so far have been addressed for next update
