### ISSUE TITLE
Structures containing unobtainable materials

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#48]
Not T1/2 here, but T3:
T3 Composter requires Vines and Ferns, both of which are presently unobtainable. Containing them is fine, but recipes might be needed for this.
Similarly T2 Sheep Pen wanted Ferns
T2 Farmers wants Seagrass

**Comment by Delfayne** [comment]
Turns out Seagrass is vanilla craftable, who knew?? I added a quest noting that

**Comment by King65868** [comment]
Vines and ferns are both craftable, but should have quests detailing how

**Comment by Saereth** [comment]
ok this should be fixed now if you guys run into more reopen it

**Comment by Saereth** [comment]
Yeah I added a tool to as well
