### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by King65868** [Saereth/inferno_issues#50]
Fishers hut gives create copper nuggets which have no use 
Silver ore has to be broken manually for ore chunks, also can’t make the block in a crafting table only by doing ore chunks in a tinkers smeltery. Block of silver can’t be turned into ingots

**Comment by Saereth** [comment]
what do you need silver chunks for? I'd prefer to remove the need for chunks

**Comment by King65868** [comment]
Slow crusher(occultism) requires ore chunks
Breaking ores manually gives chunks so don’t know if you can remove that

**Comment by Saereth** [comment]
oh yeah I already updated the crusher ritual to require inogts instead of chunks if you see any more rituials that need fixing let me know

**Comment by King65868** [comment]
Will do

**Comment by King65868** [comment]
The ore miner needs an ore chunk too, if you haven’t fixed that yet

**Comment by Saereth** [comment]
fixed all these lmk if you see more issues
