### ISSUE TITLE
Current list of recipe requests

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#51]
Sunflowers (requested by some travelers) 
Gilded Blackstone if not used for core progression
Plantation to grow Twisting Vines (if possible)
Early basalt gen
Blackstone cobble -> blackstone (in stonesmelter not stonemason)
Nether sprouts/twisting vines if plantation can't handle vines

Quark warped bookcase - this will be nice for uni. It's in the supply camp, but there's no visible recipe.

**Comment by Saereth** [comment]
added all these

**Comment by King65868** [comment]
Some more requests: tiny charcoal/coal added to colonists crafting, propelplant torch added to colonist crafting, and a way to make the ptopelplant cane with colonists

**Comment by Saereth** [comment]
aLl these are now added
