### ISSUE TITLE
More issues 7/21

### ISSUE THREAD

**Issue by King65868** [Saereth/inferno_issues#60]
Pyrowood log -> plank recipe can not be made by the carpenter 
Stripped hellbark log can’t be made by the forester* 
Tooltip for where certain saplings like pyrowood and hellbark are might be good 
Pyrowood saplings don’t seem to spawn in the nether waste biomes 
Silver ore can not be processed without manually breaking it
Silver dust is removed
Rotten flesh has 2 outputs in the blood infuser, spider eye recipe should be kept 
Travelers gear added to colonist crafting and fixing the recipe since they aren't craftable
Dark gem ore can not be processed by colonists, same with silver
Courier's hut T4 is missing a block which lets out a flow of blood
Dead horn coral fan doesn’t have a recipe, used in T4 restaurant
Experience comb should give raw experience so it can be used in the experience obelisk, and add raw experience as an option for the bottler to make xp bottles. Or could change the comb to output xp bottles in the centrifuge.
Propelplant duplication recipe would be cool
T3 flower shop has a water spill 
Alchemist Tower places random blocks outside its boundary when building
Enchanter's Tower T4 requires an end rod
Apiary(minecolonies) seems useless, maybe worth removing
Glow Litchen is needed for T4 alchemy tower, uncraftable
Liliac needs a recipe for composter hut T4
Rose bush needs a recipe, used for Mystical site T3
Rotation speed controller would make create power a lot easier
Cake recipe from colonists 
Hematophagous bee spawn egg recipe is duplicated
Burning gemstone has its default smelting recipe plus the added blood altar recipe
Inscription tool earth has its default recipe plus the added one
Undead sapling can be made in both blood altar and blood infuser(not sure if this is a bug or not)
There is a recipe for netherite scrap that has an empty tag of netherite scrap dust as input
Small laboratory furnace gives 14.5 levels of experience every time when you take out an output, unlikely you can fix this but something to note
Nickel dust is removed

**Comment by King65868** [comment]
Mechanical press doing more plates would be good, also adding zinc and brass sheets to FTBic’s rolling machine

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/180602320-c435eab7-33e7-4f86-a35f-4dc0a1cafe8a.png)
these recipes are actually different, depends on which promise acceptor you have in it

The miner was giving the wrong type of silver ore, any you still have you should throw out and spawn in thermal silver ore and the process should work, fixed this for next update.

XP liquids should all be unified now....

fixed the florist and alchemist, alchemist was way messed up, might have to rebuild

t4 enchanter requiring endrod is ok

removed apiary hut


it is intended to let the undead sapling be made in either, gives them options during their progression path is all

removed small lab furnace

rest should be fixed as of 0.2.0

**Comment by King65868** [comment]
Actually it doesn’t matter which promise acceptor you have, it only matters what the minium tier one you have. If you have at least gold it will always produce spider eyes only, leather recipe isn’t usable unless you downgrade
