### ISSUE TITLE
7/23 (1.20 release) Issues

### ISSUE THREAD

**Issue by random51** [Saereth/inferno_issues#63]
Can't craft traveler armor in smithing table as JEI suggests. Can't request it via Postbox either. Oh wait, can request it via postbox but minecolonies doesn't recognize the fletcher can make it.

Nature's Aura book still borked, will try a 100% clean install to see if it is some sort of leftover from previous versions/installs. Tried clean install, same problem.

Don't forget recipe for Ars sapling(s) to start the mod.

The output of the novice armor recipes for boots and leggings are reversed (put in boots, get leggings out of smithing table, put in leggings, get boots).

Mechanic won't accept propelplant torch recipe

**Comment by Saereth** [comment]
The nature's aura book is a mod issues, its been reported 2 days ago, will follow up with it. Ars recipe is now added, I'll look into the travels armor weirdness

**Comment by Saereth** [comment]
The armor issue is because of the bonus stats mod... -_-

**Comment by King65868** [comment]
right clicking on an eternal water source(evilcraft) with a p2p tunnel turns it into a water source
Need a shapeless recipe to turn other types of p2p -> me p2p

**Comment by King65868** [comment]
Propelplant torch recipe is under custom recipes btw

**Comment by random51** [comment]
Novice armor smithing table recipes for boots and leggings have their outputs reversed
Need recipe for brain coral fan
Could use restaurant recipe for sourceberry roll.

**Comment by random51** [comment]
Marauder armor boots/leggins swapped the same way novice armor is.

**Comment by Saereth** [comment]
> right clicking on an eternal water source(evilcraft) with a p2p tunnel turns it into a water source
This is apparently intended lol

> Ender dust(ae2) has no recipe
fixed

> Pyrowood sapling cant be put in a bonsai
added

> Rose bush needs a recipe
added 

> Tinkers tools dont give a drop when mining pyrowood logs
opened an issue with the mod author, he's using non standard drop tables so I cant override to fix

> Iesnium nugget recipe for colonists
they didnt have the forge:ingot/nugget tags should be fixed now

> Novice armor smithing table recipes for boots and leggings have their outputs reversed
fixed

> Need recipe for brain coral fan
fixed

> Could use restaurant recipe for sourceberry roll.
added
