### ISSUE TITLE
Hard Shell Spiders have persistent combat effects

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#7]
**Describe the bug**
I fled from a Hard Shell Spider into my hole. Despite being fully walled in, the spider was still both knocking me back and webbing me. Through a wall with no holes in at all.
this effect persisted even after I killed the spider. I had to relog to remove this persistent knockback/web effect

**To Reproduce**
Only had it happen once so far. Fight a spider I guess.

**Expected behavior**
Spiders to have line of sight on their effects. And to stop when they die.

**Comment by Saereth** [comment]
I think this is fixed now, reopen if not
